#!/bin/bash

MYVIMRC='~/.vimrc'
echo "$MYVIMRC"

if [ ! -d ~/.vim/autoload ]
then
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
fi



cat << EOF > $MYVIMRC

"tab stop
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
" backspace indent,eol,start
set backspace=indent,eol,start
" scan from start
set wrapscan
" curl match
set showmatch
" command candidate
set wildmenu
" wrap for kana-word
set formatoptions+=mM
" swapfile
set noswapfile
" line number
set number

### font setup
TEMPDIR="./cica_font"
wget https://github.com/miiton/Cica/releases/download/v5.0.3/Cica_v5.0.3.zip
mkdir $TEMPDIR 
unzip Cica_v5.0.3.zip -d $TEMPDIR
mkdir ~/.fonts
cp $TEMPDIR/Cica* ~/.fonts
set guifont=Cica\ 12

### vim-plug
call plug#begin()
Plug 'https://github.com/w0ng/vim-hybrid.git'
Plug 'https://github.com/preservim/nerdtree.git'
Plug 'https://github.com/vim-airline/vim-airline.git'
call plug#end()

" hint, :NERDTree for open file-tree.

### color scheme
set background=dark
colorscheme hybrid
EOF

