#!/bin/bash -e

sudo apt install zsh -y


# -------------------------------------
# prompt customize
# -------------------------------------
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

# -------------------------------------
# prompt customize
# -------------------------------------
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc



